### PR TITLE
Update installation instructions to be compile-time only

### PR DESCRIPTION
**Pull request by s3cur3**
I _believe_ this is correct (based on my reading of the code, everything in the package happens in macros), but I could be wrong. 😄

### CODE REVIEW

**Comment by bamorim** [comment]
You are right, everything is compile-time. I'll try this out to make sure.

**Comment by dvic** [comment]
I just double checked it, LGTM.

**Comment by bamorim** [comment]
Thanks, that is really useful!

I merged it, but I don't know if I can update the docs without releasing a new version and if it is worth to release a new version just for that.

**Comment by s3cur3** [comment]
Makes sense! Thanks again for a super useful library!

**Pull request merged**
