### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by dvic**

### CODE REVIEW

**Comment by dvic** [comment]
@bamorim It looks like `Code.Typespec.fetch_types(bytecode)` returns `:error`? (`TypedEctoSchemaTest.standardise/2` is being fed `nil`) Any idea why?

**Comment by bamorim** [comment]
That's a private module that IIRC we were only using for tests (I hope). This also means that it can break xD.

That being said, maybe the compilation is not including typespecs by default and we need to set an option for that?

**Comment by bamorim** [comment]
Maybe something changed in Elixir 1.14?

**Comment by bamorim** [comment]
Found this that seems to be related

https://elixirforum.com/t/enable-abstract-code-chunk-in-elixir-1-14/52514

**Comment by bamorim** [comment]
Which points to https://github.com/elixir-lang/elixir/issues/12300

Sorry for all the messages, on my phone right now.

Need to go to bed now xD

**Pull request merged**
