### PR TITLE
Add support for `foreign_key_type` attribute

### LINKED ISSUE #13: @primary_key and @foreign_key_type are not supported
I define my schema as follows:
```
use TypedEctoSchema
@primary_key {:id, :binary_id, read_after_writes: true}
@foreign_key_type :binary_id
```
but when I invoke `t MyApp.Post` in iex, then I see that typespecs  for primary key and foreign keys are still integer.
```

@type t() :: %MyApp.Post{
        __meta__: Ecto.Schema.Metadata.t(),
        id: integer() | nil,
        user: Ecto.Schema.belongs_to(MyApp.User.t()) | nil,
        user_id: integer() | nil,
      }
```

### PR DESCRIPTION
**Pull request by fuelen**
closes #13

### CODE REVIEW

**Comment by bamorim** [comment]
Hey @fuelen thanks for the contribution. Can you add a test case for that?

**Comment by fuelen** [comment]
@bamorim Done, please have take a look.

**Comment by bamorim** [comment]
Looks nice. I'll take a closer look as soon as I'm on my desk. Thanks

**Comment by bamorim** [comment]
Sorry for the delay, just realized I'm still using Travis CI on this repository execution ceased on June.

Had to clone and test and check manually locally. Thanks for the contribution.

**Pull request merged**
